name: build-and-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      build_only:
        description: 'Build only (skip creating GitHub Release)'
        required: false
        default: true
        type: boolean
      tag:
        description: 'Tag to build/release (e.g. v1.0.0). For manual test builds, leave empty.'
        required: false

jobs:
  build-macos:
    runs-on: macos-latest
    # Allow manual (workflow_dispatch) builds without tags; still run on tag pushes.
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Generate icons (.icns and .ico)
        run: |
          python scripts/make_app_icons.py

      - name: Build app (PyInstaller)
        run: |
          pyinstaller --noconfirm AdvancedAutoclicker_Modern.spec

      - name: Create DMG
        run: |
          bash scripts/create_dmg.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            dist/Advanced Autoclicker.app
            dist/AdvancedAutoclicker-macOS.dmg

  build-windows:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Generate icons (.icns and .ico)
        run: |
          python scripts/make_app_icons.py

      - name: Build app (PyInstaller)
        run: |
          pyinstaller --noconfirm AdvancedAutoclicker_Modern.spec

      - name: Zip distribution
        run: |
          Compress-Archive -Path "dist/Advanced Autoclicker" -DestinationPath "dist/AdvancedAutoclicker-Windows.zip"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/Advanced Autoclicker/**
            dist/AdvancedAutoclicker-Windows.zip

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    # Only create a release when:
    # - a tag push triggers the workflow, OR
    # - a manual run provides a tag AND explicitly disables build_only.
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.tag != '' && inputs.build_only != true)
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-artifacts
          path: macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: windows

      - name: Generate checksums
        run: |
          echo "Checksums:" > CHECKSUMS.txt
          if [ -f "macos/AdvancedAutoclicker-macOS.dmg" ]; then
            shasum -a 256 "macos/AdvancedAutoclicker-macOS.dmg" >> CHECKSUMS.txt
          fi
          find windows -maxdepth 6 -type f -name '*.exe' -print0 | xargs -0 shasum -a 256 >> CHECKSUMS.txt || true
          find windows -maxdepth 3 -type f -name 'AdvancedAutoclicker-Windows.zip' -print0 | xargs -0 shasum -a 256 >> CHECKSUMS.txt || true
          cat CHECKSUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name || inputs.tag }}
          name: Advanced Autoclicker ${{ github.ref_name || inputs.tag }}
          draft: false
          prerelease: false
          files: |
            macos/AdvancedAutoclicker-macOS.dmg
            windows/AdvancedAutoclicker-Windows.zip
            CHECKSUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
