name: build-and-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g. v1.0.0)'
        required: false

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
  if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.tag != '')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag != '' && inputs.tag || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install macOS GUI deps (PyObjC)
        run: |
          python -m pip install "pyobjc-core>=10.0" "pyobjc-framework-Quartz>=10.0" "pyobjc-framework-ApplicationServices>=10.0"

      - name: Build app (PyInstaller)
        run: |
          pyinstaller --noconfirm AdvancedAutoclicker_Modern.spec

      - name: Create DMG
        run: |
          bash scripts/create_dmg.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            dist/Advanced Autoclicker.app
            dist/AdvancedAutoclicker-macOS.dmg

  build-windows:
    runs-on: windows-latest
  if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.tag != '')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag != '' && inputs.tag || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Build app (PyInstaller)
        run: |
          pyinstaller --noconfirm AdvancedAutoclicker_Modern.spec

      - name: Zip distribution
        run: |
          if (Test-Path "dist/AdvancedAutoclicker-Windows.zip") { Remove-Item "dist/AdvancedAutoclicker-Windows.zip" -Force }
          Compress-Archive -Path "dist/Advanced Autoclicker" -DestinationPath "dist/AdvancedAutoclicker-Windows.zip" -Force

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/Advanced Autoclicker/**
            dist/AdvancedAutoclicker-Windows.zip

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.tag != '')
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-artifacts
          path: macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: windows

      - name: Generate checksums
        run: |
          echo "Checksums:" > CHECKSUMS.txt
          if [ -f "macos/AdvancedAutoclicker-macOS.dmg" ]; then
            shasum -a 256 "macos/AdvancedAutoclicker-macOS.dmg" >> CHECKSUMS.txt
          fi
          find windows -maxdepth 6 -type f -name '*.exe' -print0 | xargs -0 shasum -a 256 >> CHECKSUMS.txt || true
          find windows -maxdepth 3 -type f -name 'AdvancedAutoclicker-Windows.zip' -print0 | xargs -0 shasum -a 256 >> CHECKSUMS.txt || true
          cat CHECKSUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag != '' && inputs.tag || github.ref_name }}
          name: Advanced Autoclicker ${{ inputs.tag != '' && inputs.tag || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            macos/AdvancedAutoclicker-macOS.dmg
            windows/AdvancedAutoclicker-Windows.zip
            CHECKSUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}